\documentclass{article}\usepackage[]{graphicx}\usepackage[]{xcolor}
% maxwidth is the original width if it is less than linewidth
% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlsng}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hldef}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}
\usepackage[margin=1.0in]{geometry} % To set margins
\usepackage{amsmath}  % This allows me to use the align functionality.
                      % If you find yourself trying to replicate
                      % something you found online, ensure you're
                      % loading the necessary packages!
\usepackage{amsfonts} % Math font
\usepackage{fancyvrb}
\usepackage{hyperref} % For including hyperlinks
\usepackage[shortlabels]{enumitem}% For enumerated lists with labels specified
                                  % We had to run tlmgr_install("enumitem") in R
\usepackage{float}    % For telling R where to put a table/figure
\usepackage{natbib}        %For the bibliography
\bibliographystyle{apalike}%For the bibliography
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}


\begin{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Question 1
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\item A group of researchers is running an experiment over the course of 30 months, 
with a single observation collected at the end of each month. Let $X_1, ..., X_{30}$
denote the observations for each month. From prior studies, the researchers know that
\[X_i \sim f_X(x),\]
but the mean $\mu_X$ is unknown, and they wish to conduct the following test
\begin{align*}
H_0&: \mu_X = 0\\
H_a&: \mu_X > 0.
\end{align*}
At month $k$, they have accumulated data $X_1, ..., X_k$ and they have the 
$t$-statistic
\[T_k = \frac{\bar{X} - 0}{S_k/\sqrt{n}}.\]
The initial plan was to test the hypotheses after all data was collected (at the 
end of month 30), at level $\alpha=0.05$. However, conducting the experiment is 
expensive, so the researchers want to ``peek" at the data at the end of month 20 
to see if they can stop it early. That is, the researchers propose to check 
whether $t_{20}$ provides statistically discernible support for the alternative. 
If it does, they will stop the experiment early and report support for the 
researcher's alternative hypothesis. If it does not, they will continue to month 
30 and test whether $t_{30}$ provides statistically discernible support for the
alternative.

\begin{enumerate}
  \item What values of $t_{20}$ provide statistically discernible support for the
  alternative hypothesis?
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{mu0} \hlkwb{<-} \hlnum{0}
\hldef{alpha} \hlkwb{<-} \hlnum{0.05}
\hldef{df_20} \hlkwb{<-} \hlnum{20} \hlopt{-}\hlnum{1}
\hlcom{#get the critical value for statistically discernible support}
\hldef{critical_20} \hlkwb{<-} \hlkwd{qt}\hldef{(}\hlkwc{p} \hldef{=} \hlnum{1} \hlopt{-} \hldef{alpha,} \hlkwc{df} \hldef{= df_20)}
\hldef{critical_20}
\end{alltt}
\begin{verbatim}
## [1] 1.729133
\end{verbatim}
\end{kframe}
\end{knitrout}
The value $t_{20}$ = 1.729 provides statisticaly discernible support for the alterative hypothesis.
  \item What values of $t_{30}$ provide statistically discernible support for the
  alternative hypothesis?
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{df_30} \hlkwb{<-} \hlnum{30} \hlopt{-}\hlnum{1}
\hlcom{#get the critical value for statistically discernible support}
\hldef{critical_30} \hlkwb{<-} \hlkwd{qt}\hldef{(}\hlkwc{p} \hldef{=} \hlnum{1} \hlopt{-} \hldef{alpha,} \hlkwc{df} \hldef{= df_30)}
\hldef{critical_30}
\end{alltt}
\begin{verbatim}
## [1] 1.699127
\end{verbatim}
\end{kframe}
\end{knitrout}
The value $t_{30}$ = 1.699 provides statisticaly discernible support for the alterative hypothesis.
  \item Suppose $f_X(x)$ is a Laplace distribution with $a=0$ and $b=4.0$.
  Conduct a simulation study to assess the Type I error rate of this approach.\\
  \textbf{Note:} You can use the \texttt{rlaplace()} function from the \texttt{VGAM}
  package for \texttt{R} \citep{VGAM}.
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{#Conduct a simulation study to assess the Type I error }
\hldef{a} \hlkwb{<-} \hlnum{0}
\hldef{b} \hlkwb{<-} \hlnum{4.0}
\hldef{n.simulations} \hlkwb{<-} \hlnum{1000}
\hldef{type1.count} \hlkwb{<-} \hlnum{0} \hlcom{#count the number of times we got Type I error}

\hlcom{#conduct the simulation}
\hlkwa{for} \hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{n.simulations)\{}
\hldef{sim} \hlkwb{<-} \hlkwd{rlaplace}\hldef{(}\hlkwc{n} \hldef{=} \hlnum{30}\hldef{,} \hlkwc{location} \hldef{= a,} \hlkwc{scale} \hldef{= b)}
\hlcom{#calculate the critical point}
\hldef{t_sim} \hlkwb{<-} \hlkwd{mean}\hldef{(sim)}\hlopt{/} \hldef{(}\hlkwd{sd}\hldef{(sim)}\hlopt{/}\hlkwd{sqrt}\hldef{(}\hlnum{30}\hldef{))}

\hlcom{#check if t is larger than the critical point}
\hlkwa{if} \hldef{(t_sim} \hlopt{>} \hldef{critical_30)\{}
  \hldef{type1.count} \hlkwb{=} \hldef{type1.count} \hlopt{+} \hlnum{1}
\hldef{\}}
\hldef{\}}

\hlcom{#calculate the rate of receiving Type I error }
\hldef{rate.type1} \hlkwb{<-} \hldef{type1.count}\hlopt{/}\hldef{n.simulations}
\hldef{rate.type1}
\end{alltt}
\begin{verbatim}
## [1] 0.042
\end{verbatim}
\end{kframe}
\end{knitrout}
The Type I error rate for a Laplace distribution with $a=0$ and $b=4.0$ by using a simulation is 0.042 = 4.2\%. 
\end{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Question 2
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  \item Perform a simulation study to assess the robustness of the $T$ test. 
  Specifically, generate samples of size $n=15$ from the Beta(10,2), Beta(2,10), 
  and Beta(10,10) distributions and conduct the following hypothesis tests against 
  the actual mean for each case (e.g., $\frac{10}{10+2}$, $\frac{2}{10+2}$, and 
  $\frac{10}{10+10}$). 
  \begin{enumerate}
    \item What proportion of the time do we make an error of Type I for a
    left-tailed test?
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{n} \hlkwb{<-}\hlnum{15}
\hlcom{#calculate the true means for each of beta distributions}
\hldef{mean.beta.10.2} \hlkwb{<-} \hlnum{10}\hlopt{/}\hldef{(}\hlnum{10}\hlopt{+}\hlnum{2}\hldef{)}
\hldef{mean.beta.2.10} \hlkwb{<-} \hlnum{2}\hlopt{/}\hldef{(}\hlnum{2}\hlopt{+}\hlnum{10}\hldef{)}
\hldef{mean.beta.10.10} \hlkwb{<-} \hlnum{10}\hlopt{/}\hldef{(}\hlnum{10}\hlopt{+}\hlnum{10}\hldef{)}

\hlcom{#left-tailed test for beta(10,2)}
\hldef{count.error.left.10.2} \hlkwb{<-} \hlnum{0}
\hlcom{#perform the simulation}
\hlkwa{for} \hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{n.simulations)\{}
  \hlcom{#get a sample from beta distribution}
  \hldef{sample} \hlkwb{<-} \hlkwd{rbeta}\hldef{(n,} \hlkwc{shape1} \hldef{=} \hlnum{10}\hldef{,} \hlkwc{shape2} \hldef{=} \hlnum{2}\hldef{)}
  \hlcom{#perform a t-test on the sample}
  \hldef{t_test} \hlkwb{<-} \hlkwd{t.test}\hldef{(sample,} \hlkwc{alternative} \hldef{=} \hlsng{"less"}\hldef{,} \hlkwc{mu} \hldef{= mean.beta.10.2)}
  \hlcom{#check if we got a type 1 error}
  \hlkwa{if} \hldef{(t_test}\hlopt{$}\hldef{p.value} \hlopt{<} \hldef{alpha)\{}
\hldef{count.error.left.10.2} \hlkwb{<-} \hldef{count.error.left.10.2} \hlopt{+}\hlnum{1}
  \hldef{\}}
\hldef{\}}
\hlcom{#calculate the proportion of time we make a Type 1 error}
\hldef{rate.left.10.2} \hlkwb{<-} \hldef{count.error.left.10.2}\hlopt{/}\hldef{n.simulations}


\hlcom{#left-tailed test for beta(2,10)}
\hldef{count.error.left.2.10} \hlkwb{<-} \hlnum{0}
\hlcom{#perform the simulation}
\hlkwa{for} \hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{n.simulations)\{}
  \hlcom{#get a sample from beta distribution}
  \hldef{sample} \hlkwb{<-} \hlkwd{rbeta}\hldef{(n,} \hlkwc{shape1} \hldef{=} \hlnum{2}\hldef{,} \hlkwc{shape2} \hldef{=} \hlnum{10}\hldef{)}
  \hlcom{#perform a t-test on the sample}
  \hldef{t_test} \hlkwb{<-} \hlkwd{t.test}\hldef{(sample,} \hlkwc{alternative} \hldef{=} \hlsng{"less"}\hldef{,} \hlkwc{mu} \hldef{= mean.beta.2.10)}
  \hlcom{#check if we got a type 1 error}
  \hlkwa{if} \hldef{(t_test}\hlopt{$}\hldef{p.value} \hlopt{<} \hldef{alpha)\{}
\hldef{count.error.left.2.10} \hlkwb{<-} \hldef{count.error.left.2.10} \hlopt{+}\hlnum{1}
  \hldef{\}}
\hldef{\}}
\hlcom{#calculate the proportion of time we make a Type 1 error}
\hldef{rate.left.2.10} \hlkwb{<-} \hldef{count.error.left.2.10}\hlopt{/}\hldef{n.simulations}


\hlcom{#left-tailed test for beta(10,10)}
\hldef{count.error.left.10.10} \hlkwb{<-} \hlnum{0}
\hlcom{#perform the simulation}
\hlkwa{for} \hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{n.simulations)\{}
  \hlcom{#get a sample from beta distribution}
  \hldef{sample} \hlkwb{<-} \hlkwd{rbeta}\hldef{(n,} \hlkwc{shape1} \hldef{=} \hlnum{10}\hldef{,} \hlkwc{shape2} \hldef{=} \hlnum{10}\hldef{)}
  \hlcom{#perform a t-test on the sample}
  \hldef{t_test} \hlkwb{<-} \hlkwd{t.test}\hldef{(sample,} \hlkwc{alternative} \hldef{=} \hlsng{"less"}\hldef{,} \hlkwc{mu} \hldef{= mean.beta.10.10)}
  \hlcom{#check if we got a type 1 error}
  \hlkwa{if} \hldef{(t_test}\hlopt{$}\hldef{p.value} \hlopt{<} \hldef{alpha)\{}
\hldef{count.error.left.10.10} \hlkwb{<-} \hldef{count.error.left.10.10} \hlopt{+}\hlnum{1}
  \hldef{\}}
\hldef{\}}
\hlcom{#calculate the proportion of time we make a Type 1 error}
\hldef{rate.left.10.10} \hlkwb{<-} \hldef{count.error.left.10.10}\hlopt{/}\hldef{n.simulations}

\hldef{rate.left.10.2}
\end{alltt}
\begin{verbatim}
## [1] 0.034
\end{verbatim}
\begin{alltt}
\hldef{rate.left.2.10}
\end{alltt}
\begin{verbatim}
## [1] 0.088
\end{verbatim}
\begin{alltt}
\hldef{rate.left.10.10}
\end{alltt}
\begin{verbatim}
## [1] 0.062
\end{verbatim}
\end{kframe}
\end{knitrout}
We make an error of Type I for a left-tailed test 0.034 = 3.4\% for Beta(10,2),  0.088 = 8.8\% for Beta(2,10), and 0.062 = 6.2\% for Beta(10,10).
    \item What proportion of the time do we make an error of Type I for a
    right-tailed test?
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{#right-tailed test for beta(10,2)}
\hldef{count.error.right.10.2} \hlkwb{<-} \hlnum{0}
\hlcom{#perform the simulation}
\hlkwa{for} \hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{n.simulations)\{}
  \hlcom{#get a sample from beta distribution}
  \hldef{sample} \hlkwb{<-} \hlkwd{rbeta}\hldef{(n,} \hlkwc{shape1} \hldef{=} \hlnum{10}\hldef{,} \hlkwc{shape2} \hldef{=} \hlnum{2}\hldef{)}
  \hlcom{#perform a t-test on the sample}
  \hldef{t_test} \hlkwb{<-} \hlkwd{t.test}\hldef{(sample,} \hlkwc{alternative} \hldef{=} \hlsng{"greater"}\hldef{,} \hlkwc{mu} \hldef{= mean.beta.10.2)}
  \hlcom{#check if we got a type 1 error}
  \hlkwa{if} \hldef{(t_test}\hlopt{$}\hldef{p.value} \hlopt{<} \hldef{alpha)\{}
\hldef{count.error.right.10.2} \hlkwb{<-} \hldef{count.error.right.10.2} \hlopt{+}\hlnum{1}
  \hldef{\}}
\hldef{\}}
\hlcom{#calculate the proportion of time we make a Type 1 error}
\hldef{rate.right.10.2} \hlkwb{<-} \hldef{count.error.right.10.2}\hlopt{/}\hldef{n.simulations}


\hlcom{#right-tailed test for beta(2,10)}
\hldef{count.error.right.2.10} \hlkwb{<-} \hlnum{0}
\hlcom{#perform the simulation}
\hlkwa{for} \hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{n.simulations)\{}
  \hlcom{#get a sample from beta distribution}
  \hldef{sample} \hlkwb{<-} \hlkwd{rbeta}\hldef{(n,} \hlkwc{shape1} \hldef{=} \hlnum{2}\hldef{,} \hlkwc{shape2} \hldef{=} \hlnum{10}\hldef{)}
  \hlcom{#perform a t-test on the sample}
  \hldef{t_test} \hlkwb{<-} \hlkwd{t.test}\hldef{(sample,} \hlkwc{alternative} \hldef{=} \hlsng{"greater"}\hldef{,} \hlkwc{mu} \hldef{= mean.beta.2.10)}
  \hlcom{#check if we got a type 1 error}
  \hlkwa{if} \hldef{(t_test}\hlopt{$}\hldef{p.value} \hlopt{<} \hldef{alpha)\{}
\hldef{count.error.right.2.10} \hlkwb{<-} \hldef{count.error.right.2.10} \hlopt{+}\hlnum{1}
  \hldef{\}}
\hldef{\}}
\hlcom{#calculate the proportion of time we make a Type 1 error}
\hldef{rate.right.2.10} \hlkwb{<-} \hldef{count.error.right.2.10}\hlopt{/}\hldef{n.simulations}


\hlcom{#right-tailed test for beta(10,10)}
\hldef{count.error.right.10.10} \hlkwb{<-} \hlnum{0}
\hlcom{#perform the simulation}
\hlkwa{for} \hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{n.simulations)\{}
  \hlcom{#get a sample from beta distribution}
  \hldef{sample} \hlkwb{<-} \hlkwd{rbeta}\hldef{(n,} \hlkwc{shape1} \hldef{=} \hlnum{10}\hldef{,} \hlkwc{shape2} \hldef{=} \hlnum{10}\hldef{)}
  \hlcom{#perform a t-test on the sample}
  \hldef{t_test} \hlkwb{<-} \hlkwd{t.test}\hldef{(sample,} \hlkwc{alternative} \hldef{=} \hlsng{"greater"}\hldef{,} \hlkwc{mu} \hldef{= mean.beta.10.10)}
  \hlcom{#check if we got a type 1 error}
  \hlkwa{if} \hldef{(t_test}\hlopt{$}\hldef{p.value} \hlopt{<} \hldef{alpha)\{}
\hldef{count.error.right.10.10} \hlkwb{<-} \hldef{count.error.right.10.10} \hlopt{+}\hlnum{1}
  \hldef{\}}
\hldef{\}}
\hlcom{#calculate the proportion of time we make a Type 1 error}
\hldef{rate.right.10.10} \hlkwb{<-} \hldef{count.error.right.10.10}\hlopt{/}\hldef{n.simulations}

\hldef{rate.right.10.2}
\end{alltt}
\begin{verbatim}
## [1] 0.098
\end{verbatim}
\begin{alltt}
\hldef{rate.right.2.10}
\end{alltt}
\begin{verbatim}
## [1] 0.034
\end{verbatim}
\begin{alltt}
\hldef{rate.right.10.10}
\end{alltt}
\begin{verbatim}
## [1] 0.062
\end{verbatim}
\end{kframe}
\end{knitrout}
We make an error of Type I for a right-tailed test 0.098 = 9.8\% for Beta(10,2),  0.034 = 3.4\% for Beta(2,10), and 0.062 = 6.2\% for Beta(10,10).
    \item What proportion of the time do we make an error of Type I for a
    two-tailed test?
\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{#two-tailed test for beta(10,2)}
\hldef{count.error.two.10.2} \hlkwb{<-} \hlnum{0}
\hlcom{#perform the simulation}
\hlkwa{for} \hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{n.simulations)\{}
  \hlcom{#get a sample from beta distribution}
  \hldef{sample} \hlkwb{<-} \hlkwd{rbeta}\hldef{(n,} \hlkwc{shape1} \hldef{=} \hlnum{10}\hldef{,} \hlkwc{shape2} \hldef{=} \hlnum{2}\hldef{)}
  \hlcom{#perform a t-test on the sample}
  \hldef{t_test} \hlkwb{<-} \hlkwd{t.test}\hldef{(sample,} \hlkwc{alternative} \hldef{=} \hlsng{"two.sided"}\hldef{,} \hlkwc{mu} \hldef{= mean.beta.10.2)}
  \hlcom{#check if we got a type 1 error}
  \hlkwa{if} \hldef{(t_test}\hlopt{$}\hldef{p.value} \hlopt{<} \hldef{alpha)\{}
\hldef{count.error.two.10.2} \hlkwb{<-} \hldef{count.error.two.10.2} \hlopt{+}\hlnum{1}
  \hldef{\}}
\hldef{\}}
\hlcom{#calculate the proportion of time we make a Type 1 error}
\hldef{rate.two.10.2} \hlkwb{<-} \hldef{count.error.two.10.2}\hlopt{/}\hldef{n.simulations}


\hlcom{#two-tailed test for beta(2,10)}
\hldef{count.error.two.2.10} \hlkwb{<-} \hlnum{0}
\hlcom{#perform the simulation}
\hlkwa{for} \hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{n.simulations)\{}
  \hlcom{#get a sample from beta distribution}
  \hldef{sample} \hlkwb{<-} \hlkwd{rbeta}\hldef{(n,} \hlkwc{shape1} \hldef{=} \hlnum{2}\hldef{,} \hlkwc{shape2} \hldef{=} \hlnum{10}\hldef{)}
  \hlcom{#perform a t-test on the sample}
  \hldef{t_test} \hlkwb{<-} \hlkwd{t.test}\hldef{(sample,} \hlkwc{alternative} \hldef{=} \hlsng{"two.sided"}\hldef{,} \hlkwc{mu} \hldef{= mean.beta.2.10)}
  \hlcom{#check if we got a type 1 error}
  \hlkwa{if} \hldef{(t_test}\hlopt{$}\hldef{p.value} \hlopt{<} \hldef{alpha)\{}
\hldef{count.error.two.2.10} \hlkwb{<-} \hldef{count.error.two.2.10} \hlopt{+}\hlnum{1}
  \hldef{\}}
\hldef{\}}
\hlcom{#calculate the proportion of time we make a Type 1 error}
\hldef{rate.two.2.10} \hlkwb{<-} \hldef{count.error.two.2.10}\hlopt{/}\hldef{n.simulations}


\hlcom{#two-tailed test for beta(10,10)}
\hldef{count.error.two.10.10} \hlkwb{<-} \hlnum{0}
\hlcom{#perform the simulation}
\hlkwa{for} \hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{n.simulations)\{}
  \hlcom{#get a sample from beta distribution}
  \hldef{sample} \hlkwb{<-} \hlkwd{rbeta}\hldef{(n,} \hlkwc{shape1} \hldef{=} \hlnum{10}\hldef{,} \hlkwc{shape2} \hldef{=} \hlnum{10}\hldef{)}
  \hlcom{#perform a t-test on the sample}
  \hldef{t_test} \hlkwb{<-} \hlkwd{t.test}\hldef{(sample,} \hlkwc{alternative} \hldef{=} \hlsng{"two.sided"}\hldef{,} \hlkwc{mu} \hldef{= mean.beta.10.10)}
  \hlcom{#check if we got a type 1 error}
  \hlkwa{if} \hldef{(t_test}\hlopt{$}\hldef{p.value} \hlopt{<} \hldef{alpha)\{}
\hldef{count.error.two.10.10} \hlkwb{<-} \hldef{count.error.two.10.10} \hlopt{+}\hlnum{1}
  \hldef{\}}
\hldef{\}}
\hlcom{#calculate the proportion of time we make a Type 1 error}
\hldef{rate.two.10.10} \hlkwb{<-} \hldef{count.error.two.10.10}\hlopt{/}\hldef{n.simulations}

\hldef{rate.two.10.2}
\end{alltt}
\begin{verbatim}
## [1] 0.055
\end{verbatim}
\begin{alltt}
\hldef{rate.two.2.10}
\end{alltt}
\begin{verbatim}
## [1] 0.061
\end{verbatim}
\begin{alltt}
\hldef{rate.two.10.10}
\end{alltt}
\begin{verbatim}
## [1] 0.05
\end{verbatim}
\end{kframe}
\end{knitrout}
We make an error of Type I for a two-tailed test 0.055 = 5.5\% for Beta(10,2),  0.061 = 6.1\% for Beta(2,10), and 0.05 = 5\% for Beta(10,10).
    \item How does skewness of the underlying population distribution effect
    Type I error across the test types? \\
    For a right-skewed distribution, Beta(2,10), the Type I error is inflated for the right-tailed test. For a left-skewed distribution, Beta(10,2), the Type I error is inflated for the left-tailed test. For a symmetrical distribution, Beta(10,10), the Type I error is approximately 0.05 for all test types.
    Overall, for the left-tailed test, the right-skewed distribution has the smallest Type I error. For the right-tailed test, the left-skewed distribution has the smallest Type I error. For the two-tailed test, the symmetrical distribution has the smallest Type I error.  
  \end{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% End Document
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\end{enumerate}
\bibliography{bibliography}
\end{document}
